spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: secrets.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:magiclink
    hikari:
      username:
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8888
  h2:
    console:
      enabled: true

encryption:
  algorithm: AES
  variant: CBC
  padding: PKCS5PADDING
  secretKeyFactoryAlgorithm: PBKDF2WithHmacSHA256
  passwordIterations: 65536
  keyLength: 256
  secret:
